// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFv8FVAqQyB4GdDwxKl9D9phzK_mAHRe4',
    appId: '1:192441112220:web:eb1f7a576386b12a923f59',
    messagingSenderId: '192441112220',
    projectId: 'testmalink',
    authDomain: 'testmalink.firebaseapp.com',
    storageBucket: 'testmalink.appspot.com',
    measurementId: 'G-22ZMCN0WBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADOScXtHmMwplGL2HAL4OFWA4wYlxGbr4',
    appId: '1:192441112220:android:bb6de569dcc065f7923f59',
    messagingSenderId: '192441112220',
    projectId: 'testmalink',
    storageBucket: 'testmalink.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjf8HPxL0SO8vEmU392TLdXlpvnVnCqno',
    appId: '1:192441112220:ios:72c98422ef0354a7923f59',
    messagingSenderId: '192441112220',
    projectId: 'testmalink',
    storageBucket: 'testmalink.appspot.com',
    iosBundleId: 'com.example.flutterApplicationUts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjf8HPxL0SO8vEmU392TLdXlpvnVnCqno',
    appId: '1:192441112220:ios:72c98422ef0354a7923f59',
    messagingSenderId: '192441112220',
    projectId: 'testmalink',
    storageBucket: 'testmalink.appspot.com',
    iosBundleId: 'com.example.flutterApplicationUts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFv8FVAqQyB4GdDwxKl9D9phzK_mAHRe4',
    appId: '1:192441112220:web:21f445847616eedf923f59',
    messagingSenderId: '192441112220',
    projectId: 'testmalink',
    authDomain: 'testmalink.firebaseapp.com',
    storageBucket: 'testmalink.appspot.com',
    measurementId: 'G-60J93ZWGMT',
  );
}
